ALTER TABLE employe
	ADD CONSTRAINT PK_employe PRIMARY KEY (idE);

ALTER TABLE Admin 
	ADD CONSTRAINT PK_Admin PRIMARY KEY (idEmployee),
	ADD CONSTRAINT FK_Admin FOREIGN KEY (idEmployee) REFERENCES employe (idE);
ALTER TABLE ligue
	ADD CONSTRAINT PK_ligue PRIMARY KEY (idL)
	ADD CONSTRAINT FK_ligue FOREIGN KEY	(idAdmin) REFERENCES Admin (idEmployee);