ALTER TABLE ligue
	ADD CONSTRAINT PK_Ligue PRIMARY KEY(idL);

ALTER TABLE employe
	ADD CONSTRAINT PK_Employe PRIMARY KEY(idE),
	ADD CONSTRAINT FK_EmployeL FOREIGN KEY(idL) REFERENCES ligue(idL);

ALTER TABLE administrateur
	ADD CONSTRAINT PK_Admin PRIMARY KEY(idE, idL),
	ADD CONSTRAINT FK_AdminE FOREIGN KEY(idE) REFERENCES employe(idE),
	ADD CONSTRAINT FK_AdminL FOREIGN KEY(idL) REFERENCES ligue(idL);