ALTER TABLE ligue
	ADD CONSTRAINT PK_ligue PRIMARY KEY (idL);

ALTER TABLE employe
	ADD CONSTRAINT PK_employe PRIMARY KEY (idE),
	ADD CONSTRAINT FK_employe FOREIGN KEY (idLigue) REFERENCES Ligue (idL); 